// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbcuxnpclcyapewvherr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iY3V4bnBjbGN5YXBld3ZoZXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDU1NTAsImV4cCI6MjA2MTc4MTU1MH0.EZx0FRTzX3OcA-hDBChnmabF64yHnItDyWRVm9X2etc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);